version: "3.6"
services:
  frontend-hack:
    container_name: frontend-hack
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"

  backend-hack:
    container_name: backend-hack
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - "9000:80"